package com.jewellery.jewelleryshop.services;

import com.jewellery.jewelleryshop.entity.*;
import com.jewellery.jewelleryshop.repository.BillItemRepository;
import com.jewellery.jewelleryshop.repository.BillRepository;
import com.jewellery.jewelleryshop.repository.CustomerRepositry;
import com.jewellery.jewelleryshop.repository.JewelleryItemRepository;
import com.jewellery.jewelleryshop.repository.PaymentHistoryRepository;
import com.jewellery.jewelleryshop.repository.GstInvoiceRepository;
import com.jewellery.jewelleryshop.repository.GstInvoiceItemRepository;
import com.jewellery.jewelleryshop.repository.GstExchangeItemRepository;
import com.jewellery.jewelleryshop.repository.GstPaymentHistoryRepository;

import jakarta.transaction.Transactional;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.InputStream;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * Restores Mohit Jewellers database from the Excel backup
 * generated by BackupService.
 */
@Service
public class RestoreService {

    private final CustomerRepositry customerRepository;
    private final BillRepository billRepository;
    private final BillItemRepository billItemRepository;
    private final JewelleryItemRepository jewelleryItemRepository;
    private final PaymentHistoryRepository paymentHistoryRepository;
    private final GstInvoiceRepository gstInvoiceRepository;
    private final GstInvoiceItemRepository gstInvoiceItemRepository;
    private final GstExchangeItemRepository gstExchangeItemRepository;
    private final GstPaymentHistoryRepository gstPaymentHistoryRepository;

    private static final DateTimeFormatter DATE_TIME_FORMATTER =
            DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    public RestoreService(
            CustomerRepositry customerRepository,
            BillRepository billRepository,
            BillItemRepository billItemRepository,
            JewelleryItemRepository jewelleryItemRepository,
            PaymentHistoryRepository paymentHistoryRepository,
            GstInvoiceRepository gstInvoiceRepository,
            GstInvoiceItemRepository gstInvoiceItemRepository,
            GstExchangeItemRepository gstExchangeItemRepository,
            GstPaymentHistoryRepository gstPaymentHistoryRepository
    ) {
        this.customerRepository = customerRepository;
        this.billRepository = billRepository;
        this.billItemRepository = billItemRepository;
        this.jewelleryItemRepository = jewelleryItemRepository;
        this.paymentHistoryRepository = paymentHistoryRepository;
        this.gstInvoiceRepository = gstInvoiceRepository;
        this.gstInvoiceItemRepository = gstInvoiceItemRepository;
        this.gstExchangeItemRepository = gstExchangeItemRepository;
        this.gstPaymentHistoryRepository = gstPaymentHistoryRepository;
    }

    /**
     * Complete database restore.
     *
     * IMPORTANT:
     * Existing database data will be replaced.
     */
    @Transactional
    public String restoreFromExcel(MultipartFile file) {

        if (file == null || file.isEmpty()) {
            throw new RuntimeException("Please select a valid Excel backup file.");
        }

        String fileName = file.getOriginalFilename();

        if (fileName == null ||
                (!fileName.toLowerCase().endsWith(".xlsx")
                        && !fileName.toLowerCase().endsWith(".xls"))) {

            throw new RuntimeException(
                    "Invalid file format. Please select an Excel (.xlsx) backup file."
            );
        }

        try (InputStream inputStream = file.getInputStream();
             Workbook workbook = new XSSFWorkbook(inputStream)) {

            validateWorkbook(workbook);

            /*
             * =========================================================
             * STEP 1
             * DELETE EXISTING DATA
             * =========================================================
             *
             * FK order:
             *
             * PaymentHistory
             * BillItems
             * Bills
             * JewelleryItems
             * Customers
             */

            // GST payment history is independent from normal PaymentHistory.
            gstPaymentHistoryRepository.deleteAllInBatch();

            // GstInvoice has cascade + orphanRemoval for its GST items/exchange items.
            // deleteAll() is intentionally used instead of deleteAllInBatch()
            // so JPA cascade/orphanRemoval can clean child records safely.
            gstInvoiceRepository.deleteAll();

            paymentHistoryRepository.deleteAllInBatch();
            billItemRepository.deleteAllInBatch();
            billRepository.deleteAllInBatch();
            jewelleryItemRepository.deleteAllInBatch();
            customerRepository.deleteAllInBatch();

            /*
             * =========================================================
             * STEP 2
             * RESTORE CUSTOMERS
             * =========================================================
             */

            restoreCustomers(workbook.getSheet("Customers"));

            /*
             * =========================================================
             * STEP 3
             * RESTORE STOCK
             * =========================================================
             */

            restoreStock(workbook.getSheet("Stock"));

            /*
             * =========================================================
             * STEP 4
             * RESTORE BILLS
             * =========================================================
             */

            restoreBills(workbook.getSheet("Bills"));

            /*
             * =========================================================
             * STEP 5
             * RESTORE BILL ITEMS
             * =========================================================
             */

            restoreBillItems(workbook.getSheet("Bill Items"));

            /*
             * =========================================================
             * STEP 6
             * RESTORE PAYMENTS
             * =========================================================
             */

            restorePayments(workbook.getSheet("Payments"));

            /*
             * =========================================================
             * STEP 7
             * RESTORE GST INVOICES
             * =========================================================
             */

            restoreGstInvoices(workbook.getSheet("GST Invoices"));

            /*
             * =========================================================
             * STEP 8
             * RESTORE GST INVOICE ITEMS
             * =========================================================
             */

            restoreGstInvoiceItems(
                    workbook.getSheet("GST Invoice Items")
            );

            /*
             * =========================================================
             * STEP 9
             * RESTORE GST EXCHANGE ITEMS
             * =========================================================
             */

            restoreGstExchangeItems(
                    workbook.getSheet("GST Exchange Items")
            );

            /*
             * =========================================================
             * STEP 10
             * RESTORE GST PAYMENTS
             * =========================================================
             */

            restoreGstPayments(
                    workbook.getSheet("GST Payments")
            );

            /*
             * Outstanding sheet is NOT restored separately.
             *
             * Outstanding is derived from:
             *
             * Bill.grandTotal
             * Bill.paidAmount
             * Bill.dueAmount
             *
             * Therefore inserting it separately would create
             * duplicate/inconsistent information.
             */

            return "Database restored successfully.";

        } catch (Exception e) {

            throw new RuntimeException(
                    "Restore failed. Database changes have been rolled back.",
                    e
            );
        }
    }

    // ============================================================
    // VALIDATE WORKBOOK
    // ============================================================

    private void validateWorkbook(Workbook workbook) {

        String[] requiredSheets = {
                "Customers",
                "Bills",
                "Bill Items",
                "Stock",
                "Payments",
                "Outstanding",
                "GST Invoices",
                "GST Invoice Items",
                "GST Exchange Items",
                "GST Payments"
        };

        for (String sheetName : requiredSheets) {

            if (workbook.getSheet(sheetName) == null) {

                throw new RuntimeException(
                        "Invalid backup file. Missing sheet: " + sheetName
                );
            }
        }
    }

    // ============================================================
    // CUSTOMERS
    // ============================================================

    private void restoreCustomers(Sheet sheet) {

        int restored = 0;

        for (int rowIndex = 3; rowIndex <= sheet.getLastRowNum(); rowIndex++) {

            Row row = sheet.getRow(rowIndex);

            if (isEmptyRow(row)) {
                continue;
            }

            String customerName = getString(row, 1);
            String mobileNumber = getString(row, 2);
            String place = getString(row, 3);
            String createdDateString = getString(row, 4);

            if (mobileNumber.isBlank()) {
                throw new RuntimeException(
                        "Customer restore failed at Excel row "
                                + (rowIndex + 1)
                                + ": Mobile Number is empty."
                );
            }

            Customer customer = Customer.builder()
                    .customerName(customerName)
                    .mobileNumber(mobileNumber)
                    .place(place)
                    .build();

            Customer savedCustomer = customerRepository.save(customer);

            /*
             * Customer has @PrePersist which automatically sets
             * createdDate to current time.
             *
             * We restore the original backup date after save.
             */
            if (!createdDateString.isBlank()) {

                savedCustomer.setCreatedDate(
                        parseDate(createdDateString)
                );

                customerRepository.save(savedCustomer);
            }

            restored++;
        }

        System.out.println(
                "Customers restored: " + restored
        );
    }

    // ============================================================
    // STOCK
    // ============================================================

    private void restoreStock(Sheet sheet) {

        int restored = 0;

        for (int rowIndex = 3; rowIndex <= sheet.getLastRowNum(); rowIndex++) {

            Row row = sheet.getRow(rowIndex);

            if (isEmptyRow(row)) {
                continue;
            }

            String itemCode = getString(row, 1);
            String itemName = getString(row, 2);
            String categoryString = getString(row, 3);
            String purityString = getString(row, 4);

            BigDecimal weight = getDecimal(row, 5);
            Integer stockQuantity = getInteger(row, 6);

            String createdDateString = getString(row, 7);

            if (itemCode.isBlank()) {

                throw new RuntimeException(
                        "Stock restore failed at Excel row "
                                + (rowIndex + 1)
                                + ": Item Code is empty."
                );
            }

            JewelleryItem item = JewelleryItem.builder()
                    .itemCode(itemCode)
                    .itemName(itemName)
                    .category(parseEnum(
                            Category.class,
                            categoryString,
                            "Category",
                            rowIndex
                    ))
                    .purity(parseEnum(
                            Purity.class,
                            purityString,
                            "Purity",
                            rowIndex
                    ))
                    .weight(weight)
                    .stockQuantity(stockQuantity)
                    .build();

            JewelleryItem savedItem =
                    jewelleryItemRepository.save(item);

            /*
             * Preserve original created date.
             */
            if (!createdDateString.isBlank()) {

                savedItem.setCreatedDate(
                        parseDate(createdDateString)
                );

                jewelleryItemRepository.save(savedItem);
            }

            restored++;
        }

        System.out.println(
                "Stock items restored: " + restored
        );
    }

    // ============================================================
    // BILLS
    // ============================================================

    private void restoreBills(Sheet sheet) {

        int restored = 0;

        for (int rowIndex = 3; rowIndex <= sheet.getLastRowNum(); rowIndex++) {

            Row row = sheet.getRow(rowIndex);

            if (isEmptyRow(row)) {
                continue;
            }

            String billNumber = getString(row, 1);
            String customerName = getString(row, 2);
            String customerMobile = getString(row, 3);
            String billDateString = getString(row, 4);

            if (billNumber.isBlank()) {

                throw new RuntimeException(
                        "Bill restore failed at Excel row "
                                + (rowIndex + 1)
                                + ": Bill Number is empty."
                );
            }

            /*
             * Find customer by mobile number.
             *
             * Customer ID from old database is NOT reused.
             */
            Customer customer = null;

            if (!customerMobile.isBlank()) {

                customer = customerRepository
                        .findByMobileNumber(customerMobile)
                        .orElse(null);

                if (customer == null) {

                    throw new RuntimeException(
                            "Bill " + billNumber
                                    + " refers to customer mobile "
                                    + customerMobile
                                    + " but customer was not found."
                    );
                }
            }

            Bill bill = Bill.builder()
                    .billNumber(billNumber)
                    .customer(customer)
                    .totalAmount(getDecimal(row, 5))
                    .discount(getDecimal(row, 6))
                    .gstAmount(getDecimal(row, 7))
                    .grandTotal(getDecimal(row, 8))
                    .paidAmount(getDecimal(row, 9))
                    .dueAmount(getDecimal(row, 10))

                    .goldExchangeWeight(getDecimal(row, 11))
                    .goldExchangeRate(getDecimal(row, 12))
                    .goldExchangeAmount(getDecimal(row, 13))

                    .silverExchangeWeight(getDecimal(row, 14))
                    .silverExchangeRate(getDecimal(row, 15))
                    .silverExchangeAmount(getDecimal(row, 16))

                    .totalExchangeAmount(getDecimal(row, 17))

                    .status(parseEnum(
                            BillStatus.class,
                            getString(row, 18),
                            "Bill Status",
                            rowIndex
                    ))

                    .paymentMode(parseEnum(
                            PaymentMode.class,
                            getString(row, 19),
                            "Payment Mode",
                            rowIndex
                    ))

                    .build();

            /*
             * @PrePersist sets billDate to current time.
             *
             * Save first, then restore original date.
             */
            Bill savedBill = billRepository.save(bill);

            if (!billDateString.isBlank()) {

                savedBill.setBillDate(
                        parseDate(billDateString)
                );

                billRepository.save(savedBill);
            }

            restored++;
        }

        System.out.println(
                "Bills restored: " + restored
        );
    }

    // ============================================================
    // BILL ITEMS
    // ============================================================

    private void restoreBillItems(Sheet sheet) {

        int restored = 0;

        for (int rowIndex = 3; rowIndex <= sheet.getLastRowNum(); rowIndex++) {

            Row row = sheet.getRow(rowIndex);

            if (isEmptyRow(row)) {
                continue;
            }

            String billNumber = getString(row, 0);
            String stockItemCode = getString(row, 2);
            String itemName = getString(row, 3);

            if (billNumber.isBlank()) {

                throw new RuntimeException(
                        "Bill Item restore failed at Excel row "
                                + (rowIndex + 1)
                                + ": Bill Number is empty."
                );
            }

            /*
             * Find restored Bill by Bill Number.
             */
            Bill bill = billRepository
                    .findByBillNumber(billNumber)
                    .orElseThrow(() ->
                            new RuntimeException(
                                    "Bill Item refers to Bill "
                                            + billNumber
                                            + " but Bill was not found."
                            )
                    );

            /*
             * Manual billing items do not have stock item code.
             *
             * Stock billing items DO have item code.
             */
            JewelleryItem jewelleryItem = null;

            if (!stockItemCode.isBlank()) {

                jewelleryItem =
                        jewelleryItemRepository
                                .findByItemCode(stockItemCode)
                                .orElseThrow(() ->
                                        new RuntimeException(
                                                "Bill Item refers to stock item "
                                                        + stockItemCode
                                                        + " but Stock Item was not found."
                                        )
                                );
            }

            BillItem billItem = BillItem.builder()
                    .bill(bill)
                    .jewelleryItem(jewelleryItem)
                    .itemName(itemName)

                    .weight(getDecimal(row, 4))
                    .quantity(getInteger(row, 5))

                    .metalRate(getDecimal(row, 6))
                    .metalAmount(getDecimal(row, 7))

                    .makingChargePercent(getDecimal(row, 8))
                    .makingChargeType(getString(row, 9))
                    .makingChargeValue(getDecimal(row, 10))
                    .makingChargeAmount(getDecimal(row, 11))

                    .gstPercent(getDecimal(row, 12))
                    .gstAmount(getDecimal(row, 13))

                    .total(getDecimal(row, 14))

                    .build();

            billItemRepository.save(billItem);

            restored++;
        }

        System.out.println(
                "Bill items restored: " + restored
        );
    }

    // ============================================================
    // PAYMENTS
    // ============================================================

    private void restorePayments(Sheet sheet) {

        int restored = 0;

        for (int rowIndex = 3; rowIndex <= sheet.getLastRowNum(); rowIndex++) {

            Row row = sheet.getRow(rowIndex);

            if (isEmptyRow(row)) {
                continue;
            }

            String billNumber = getString(row, 1);
            String customerName = getString(row, 2);
            String customerMobile = getString(row, 3);

            BigDecimal amount = getDecimal(row, 4);

            String paymentDateString = getString(row, 5);

            String paymentModeString = getString(row, 6);

            if (billNumber.isBlank()) {

                throw new RuntimeException(
                        "Payment restore failed at Excel row "
                                + (rowIndex + 1)
                                + ": Bill Number is empty."
                );
            }

            Bill bill = billRepository
                    .findByBillNumber(billNumber)
                    .orElseThrow(() ->
                            new RuntimeException(
                                    "Payment refers to Bill "
                                            + billNumber
                                            + " but Bill was not found."
                            )
                    );

            /*
             * PaymentHistory requires a Customer.
             *
             * First try mobile number from Excel.
             * If it is empty, use the Bill customer.
             */
            Customer customer = null;

            if (!customerMobile.isBlank()) {

                customer = customerRepository
                        .findByMobileNumber(customerMobile)
                        .orElse(null);
            }

            if (customer == null) {
                customer = bill.getCustomer();
            }

            if (customer == null) {

                throw new RuntimeException(
                        "Payment for Bill "
                                + billNumber
                                + " has no valid Customer."
                );
            }

            PaymentHistory payment = PaymentHistory.builder()
                    .bill(bill)
                    .customer(customer)
                    .amount(amount)
                    .paymentMode(parseEnum(
                            PaymentMode.class,
                            paymentModeString,
                            "Payment Mode",
                            rowIndex
                    ))
                    .build();

            /*
             * @PrePersist automatically sets current date.
             */
            PaymentHistory savedPayment =
                    paymentHistoryRepository.save(payment);

            /*
             * Restore original payment date.
             */
            if (!paymentDateString.isBlank()) {

                savedPayment.setPaymentDate(
                        parseDate(paymentDateString)
                );

                paymentHistoryRepository.save(savedPayment);
            }

            restored++;
        }

        System.out.println(
                "Payments restored: " + restored
        );
    }



    // ============================================================
    // GST INVOICES
    // ============================================================

    private void restoreGstInvoices(Sheet sheet) {

        int restored = 0;

        for (int rowIndex = 3; rowIndex <= sheet.getLastRowNum(); rowIndex++) {

            Row row = sheet.getRow(rowIndex);

            if (isEmptyRow(row)) {
                continue;
            }

            String invoiceNumber = getString(row, 1);

            if (invoiceNumber.isBlank()) {
                throw new RuntimeException(
                        "GST Invoice restore failed at Excel row "
                                + (rowIndex + 1)
                                + ": Invoice Number is empty."
                );
            }

            String invoiceDateString = getString(row, 3);

            GstInvoice invoice = GstInvoice.builder()
                    .invoiceNumber(invoiceNumber)
                    .financialYear(getString(row, 2))
                    .invoiceDateTime(
                            invoiceDateString.isBlank()
                                    ? LocalDateTime.now()
                                    : parseDate(invoiceDateString)
                    )
                    .placeOfSupply(getString(row, 4))
                    .placeOfSupplyStateCode(getString(row, 5))
                    .sellerGstin(getString(row, 6))
                    .customerName(getString(row, 7))
                    .customerMobile(getString(row, 8))
                    .customerAddress(getString(row, 9))
                    .customerGstin(getString(row, 10))
                    .taxableAmount(getDecimal(row, 11))
                    .cgstAmount(getDecimal(row, 12))
                    .sgstAmount(getDecimal(row, 13))
                    .igstAmount(getDecimal(row, 14))
                    .totalGstAmount(getDecimal(row, 15))
                    .discountAmount(getDecimal(row, 16))
                    .roundOff(getDecimal(row, 17))
                    .grandTotal(getDecimal(row, 18))
                    .totalExchangeAmount(getDecimal(row, 19))
                    .cashAmount(getDecimal(row, 20))
                    .upiAmount(getDecimal(row, 21))
                    .cardAmount(getDecimal(row, 22))
                    .otherAmount(getDecimal(row, 23))
                    .paidAmount(getDecimal(row, 24))
                    .dueAmount(getDecimal(row, 25))
                    .paymentStatus(getString(row, 26))
                    .reverseCharge(
                            "TRUE".equalsIgnoreCase(getString(row, 27))
                    )
                    .build();

            gstInvoiceRepository.save(invoice);

            restored++;
        }

        System.out.println(
                "GST invoices restored: " + restored
        );
    }


    // ============================================================
    // GST INVOICE ITEMS
    // ============================================================

    private void restoreGstInvoiceItems(Sheet sheet) {

        int restored = 0;

        for (int rowIndex = 3; rowIndex <= sheet.getLastRowNum(); rowIndex++) {

            Row row = sheet.getRow(rowIndex);

            if (isEmptyRow(row)) {
                continue;
            }

            String invoiceNumber = getString(row, 0);

            if (invoiceNumber.isBlank()) {
                throw new RuntimeException(
                        "GST Invoice Item restore failed at Excel row "
                                + (rowIndex + 1)
                                + ": Invoice Number is empty."
                );
            }

            GstInvoice invoice =
                    gstInvoiceRepository
                            .findByInvoiceNumber(invoiceNumber)
                            .orElseThrow(() ->
                                    new RuntimeException(
                                            "GST Invoice Item refers to GST Invoice "
                                                    + invoiceNumber
                                                    + " but GST Invoice was not found."
                                    )
                            );

            GstInvoiceItem item = GstInvoiceItem.builder()
                    .gstInvoice(invoice)
                    .itemCode(getString(row, 2))
                    .itemName(getString(row, 3))
                    .hsnCode(getString(row, 4))
                    .metalType(getString(row, 5))
                    .purity(getString(row, 6))
                    .quantity(getDecimal(row, 7))
                    .weight(getDecimal(row, 8))
                    .metalRate(getDecimal(row, 9))
                    .metalAmount(getDecimal(row, 10))
                    .makingChargeType(getString(row, 11))
                    .makingChargeValue(getDecimal(row, 12))
                    .makingChargeAmount(getDecimal(row, 13))
                    .discountAmount(getDecimal(row, 14))
                    .taxableAmount(getDecimal(row, 15))
                    .gstPercent(getDecimal(row, 16))
                    .cgstAmount(getDecimal(row, 17))
                    .sgstAmount(getDecimal(row, 18))
                    .igstAmount(getDecimal(row, 19))
                    .totalAmount(getDecimal(row, 20))
                    .build();

            gstInvoiceItemRepository.save(item);

            restored++;
        }

        System.out.println(
                "GST invoice items restored: " + restored
        );
    }


    // ============================================================
    // GST EXCHANGE ITEMS
    // ============================================================

    private void restoreGstExchangeItems(Sheet sheet) {

        int restored = 0;

        for (int rowIndex = 3; rowIndex <= sheet.getLastRowNum(); rowIndex++) {

            Row row = sheet.getRow(rowIndex);

            if (isEmptyRow(row)) {
                continue;
            }

            String invoiceNumber = getString(row, 0);

            if (invoiceNumber.isBlank()) {
                throw new RuntimeException(
                        "GST Exchange Item restore failed at Excel row "
                                + (rowIndex + 1)
                                + ": Invoice Number is empty."
                );
            }

            GstInvoice invoice =
                    gstInvoiceRepository
                            .findByInvoiceNumber(invoiceNumber)
                            .orElseThrow(() ->
                                    new RuntimeException(
                                            "GST Exchange Item refers to GST Invoice "
                                                    + invoiceNumber
                                                    + " but GST Invoice was not found."
                                    )
                            );

            GstExchangeItem item = GstExchangeItem.builder()
                    .gstInvoice(invoice)
                    .metalType(getString(row, 2))
                    .weight(getDecimal(row, 3))
                    .rate(getDecimal(row, 4))
                    .amount(getDecimal(row, 5))
                    .build();

            gstExchangeItemRepository.save(item);

            restored++;
        }

        System.out.println(
                "GST exchange items restored: " + restored
        );
    }


    // ============================================================
    // GST PAYMENTS
    // ============================================================

    private void restoreGstPayments(Sheet sheet) {

        int restored = 0;

        for (int rowIndex = 3; rowIndex <= sheet.getLastRowNum(); rowIndex++) {

            Row row = sheet.getRow(rowIndex);

            if (isEmptyRow(row)) {
                continue;
            }

            String invoiceNumber = getString(row, 1);

            if (invoiceNumber.isBlank()) {
                throw new RuntimeException(
                        "GST Payment restore failed at Excel row "
                                + (rowIndex + 1)
                                + ": Invoice Number is empty."
                );
            }

            GstPaymentHistory payment =
                    GstPaymentHistory.builder()
                            .invoiceNumber(invoiceNumber)
                            .customerName(getString(row, 2))
                            .customerMobile(getString(row, 3))
                            .amount(getDecimal(row, 4))
                            .paymentDate(
                                    getString(row, 5).isBlank()
                                            ? LocalDateTime.now()
                                            : parseDate(getString(row, 5))
                            )
                            .paymentMode(getString(row, 6))
                            .build();

            gstPaymentHistoryRepository.save(payment);

            restored++;
        }

        System.out.println(
                "GST payments restored: " + restored
        );
    }

    // ============================================================
    // EXCEL HELPERS
    // ============================================================

    private String getString(Row row, int columnIndex) {

        if (row == null) {
            return "";
        }

        Cell cell = row.getCell(columnIndex);

        if (cell == null) {
            return "";
        }

        DataFormatter formatter = new DataFormatter();

        return formatter
                .formatCellValue(cell)
                .trim();
    }

    private BigDecimal getDecimal(Row row, int columnIndex) {

        if (row == null) {
            return BigDecimal.ZERO;
        }

        Cell cell = row.getCell(columnIndex);

        if (cell == null) {
            return BigDecimal.ZERO;
        }

        try {

            if (cell.getCellType() == CellType.NUMERIC) {

                return BigDecimal.valueOf(
                        cell.getNumericCellValue()
                );
            }

            String value =
                    new DataFormatter()
                            .formatCellValue(cell)
                            .trim();

            if (value.isBlank()) {
                return BigDecimal.ZERO;
            }

            return new BigDecimal(value);

        } catch (Exception e) {

            throw new RuntimeException(
                    "Invalid numeric value at Excel row "
                            + (row.getRowNum() + 1)
                            + ", column "
                            + (columnIndex + 1)
            );
        }
    }

    private Integer getInteger(Row row, int columnIndex) {

        BigDecimal decimal =
                getDecimal(row, columnIndex);

        return decimal.intValue();
    }

    private LocalDateTime parseDate(String value) {

        try {

            return LocalDateTime.parse(
                    value.trim(),
                    DATE_TIME_FORMATTER
            );

        } catch (Exception e) {

            throw new RuntimeException(
                    "Invalid date format: "
                            + value
                            + ". Expected dd-MM-yyyy HH:mm:ss"
            );
        }
    }

    private <E extends Enum<E>> E parseEnum(
            Class<E> enumClass,
            String value,
            String fieldName,
            int rowIndex
    ) {

        if (value == null || value.isBlank()) {
            return null;
        }

        try {

            return Enum.valueOf(
                    enumClass,
                    value.trim().toUpperCase()
            );

        } catch (Exception e) {

            throw new RuntimeException(
                    "Invalid "
                            + fieldName
                            + " value '"
                            + value
                            + "' at Excel row "
                            + (rowIndex + 1)
            );
        }
    }

    private boolean isEmptyRow(Row row) {

        if (row == null) {
            return true;
        }

        for (int i = 0; i < row.getLastCellNum(); i++) {

            if (!getString(row, i).isBlank()) {
                return false;
            }
        }

        return true;
    }
}